import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'excercise.mapper.dart';

@MappableClass()
class Excercise with ExcerciseMappable {
  final int exerciseId;
  final String name;
  final String force;
  final String level;
  final String mechanic;
  final String equipment;
  final List<String> primaryMuscles;
  final List<String> secondaryMuscles;
  final List<String> instructions;
  final String category;
  final List<String> images;

  Excercise({
    required this.exerciseId,
    required this.name,
    required this.force,
    required this.level,
    required this.mechanic,
    required this.equipment,
    required this.primaryMuscles,
    required this.secondaryMuscles,
    required this.instructions,
    required this.category,
    required this.images,
  });
}
