targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true # (default)
          # To use ISO 8601 strings
          # store_date_time_values_as_text: true
          databases:
            default: lib/src/common/providers/db.dart
