import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'excercise.mapper.dart';

@MappableClass()
class Exercise with ExerciseMappable {
  @MappableField(key: 'exercise_id')
  final int exerciseId;
  final String name;
  final String? force;
  final String level;
  final String? mechanic;
  final String? equipment;
  @MappableField(key: 'primary_muscles')
  final List<String> primaryMuscles;
  @MappableField(key: 'secondary_muscles')
  final List<String> secondaryMuscles;
  final List<String> instructions;
  final String category;
  final List<String> images;

  Exercise({
    required this.exerciseId,
    required this.name,
    required this.force,
    required this.level,
    required this.mechanic,
    required this.equipment,
    required this.primaryMuscles,
    required this.secondaryMuscles,
    required this.instructions,
    required this.category,
    required this.images,
  });
}
